/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accounting.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nayan
 */
public class Find extends javax.swing.JFrame {

    /**
     * Creates new form Find
     */
    public Find() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        home = new javax.swing.JMenuItem();
        item = new javax.swing.JMenuItem();
        customer1 = new javax.swing.JMenuItem();
        ven = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        phis = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        shis = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jScrollPane1 = new javax.swing.JScrollPane();
        customer = new javax.swing.JTable();
        searchbar = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        vendor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        home1 = new javax.swing.JMenuItem();
        item1 = new javax.swing.JMenuItem();
        customer2 = new javax.swing.JMenuItem();
        ven1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        phis1 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        shis1 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();

        jMenuBar1.setBackground(new java.awt.Color(102, 0, 153));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setForeground(new java.awt.Color(153, 0, 153));
        jMenuBar1.setAlignmentY(0.5F);
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu1.setText("Account Master       ");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        home.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jMenu1.add(home);

        item.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        item.setText("Item");
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActionPerformed(evt);
            }
        });
        jMenu1.add(item);

        customer1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        customer1.setText("Customer");
        customer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer1ActionPerformed(evt);
            }
        });
        jMenu1.add(customer1);

        ven.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ven.setText("Vendor");
        ven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venActionPerformed(evt);
            }
        });
        jMenu1.add(ven);

        jMenuItem4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuItem4.setText("Find");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuItem7.setForeground(new java.awt.Color(255, 0, 51));
        jMenuItem7.setText("Logout");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Purchase          ");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuItem2.setText("Purchase Form");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        phis.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        phis.setText("Purchase History");
        phis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phisActionPerformed(evt);
            }
        });
        jMenu2.add(phis);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sales             ");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuItem3.setText("Sales Form");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        shis.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        shis.setText("Sales History");
        shis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shisActionPerformed(evt);
            }
        });
        jMenu3.add(shis);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Report           ");
        jMenu5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuItem1.setText("STOCK");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);
        jMenu5.add(jSeparator1);

        jMenuBar1.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 935, 602));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "city", "phone"
            }
        ));
        jScrollPane1.setViewportView(customer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 158, -1, -1));
        getContentPane().add(searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 63, 681, 57));

        search.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 63, 149, 57));

        vendor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "city", "phone"
            }
        ));
        jScrollPane2.setViewportView(vendor);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 158, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("CUSTOMER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 129, 160, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("VENDOR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 150, 30));

        jMenuBar2.setBackground(new java.awt.Color(102, 0, 153));
        jMenuBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar2.setForeground(new java.awt.Color(153, 0, 153));
        jMenuBar2.setAlignmentY(0.5F);
        jMenuBar2.setBorderPainted(false);
        jMenuBar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu4.setText("Account Master       ");
        jMenu4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        home1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        home1.setText("Home");
        home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home1ActionPerformed(evt);
            }
        });
        jMenu4.add(home1);

        item1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        item1.setText("Item");
        item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item1ActionPerformed(evt);
            }
        });
        jMenu4.add(item1);

        customer2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        customer2.setText("Customer");
        customer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer2ActionPerformed(evt);
            }
        });
        jMenu4.add(customer2);

        ven1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ven1.setText("Vendor");
        ven1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ven1ActionPerformed(evt);
            }
        });
        jMenu4.add(ven1);

        jMenuItem5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuItem5.setText("Find");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar2.add(jMenu4);

        jMenu6.setText("Purchase          ");
        jMenu6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuItem6.setText("Purchase Form");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        phis1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        phis1.setText("Purchase History");
        phis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phis1ActionPerformed(evt);
            }
        });
        jMenu6.add(phis1);

        jMenuBar2.add(jMenu6);

        jMenu7.setText("Sales             ");
        jMenu7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuItem9.setText("Sales Form");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem9);

        shis1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        shis1.setText("Sales History");
        shis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shis1ActionPerformed(evt);
            }
        });
        jMenu7.add(shis1);

        jMenuBar2.add(jMenu7);

        jMenu8.setText("Report           ");
        jMenu8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jMenuItem10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuItem10.setText("STOCK");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem10);
        jMenu8.add(jSeparator2);

        jMenuBar2.add(jMenu8);

        setJMenuBar(jMenuBar2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
       try{
        Connection con=Connect.getconn();
         DefaultTableModel tb2Model=(DefaultTableModel)vendor.getModel();
         tb2Model.setRowCount(0);
          DefaultTableModel tb3Model=(DefaultTableModel)customer.getModel();
          tb3Model.setRowCount(0);
     PreparedStatement ps=con.prepareStatement("select id,cname,city,phone from customer where cname like ? ");
     String s=searchbar.getText();
     ps.setString(1,"%"+s+"%");
     ResultSet rs=ps.executeQuery();
     while(rs.next())
     {
        // System.out.println("heelo");
         String id=String.valueOf(rs.getInt("id"));
         String cname=rs.getString("cname");
         String city=rs.getString("city");
         String phone=rs.getString("phone");
         String tbData[]={id,cname,city,phone};
            DefaultTableModel tb1Model=(DefaultTableModel)customer.getModel();
            tb1Model.addRow(tbData);
     }
    // ps.close();
     //con.close();
     //Connection con1=Connect.getConn();
     PreparedStatement pp=con.prepareStatement("select id,vname,city,phone from vendor where vname like ? ");
     pp.setString(1,"%"+s+"%");
     ResultSet rp=pp.executeQuery();
     while(rp.next())
     {
         String id=String.valueOf(rp.getInt("id"));
         String vname=rp.getString("vname");
         String city=rp.getString("city");
         String phone=rp.getString("phone");
         String tData[]={id,vname,city,phone};
            DefaultTableModel tbModel=(DefaultTableModel)vendor.getModel();
            tbModel.addRow(tData);
     }
       }catch(Exception tt)
       {
           System.out.println(tt);
       }
   searchbar.setText("");

    }//GEN-LAST:event_searchActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        this.setVisible(false);
        Accountsyst.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActionPerformed
        this.setVisible(false);
        Addproduct.main(new String[3]);

    }//GEN-LAST:event_itemActionPerformed

    private void customer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer1ActionPerformed
        this.setVisible(false);
        Customer.main(new String[2]);
    }//GEN-LAST:event_customer1ActionPerformed

    private void venActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venActionPerformed
        this.setVisible(false);
        Vendor.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_venActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.setVisible(false);
        Find.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        this.setVisible(false);
        Login.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setVisible(false);
        Purchase.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void phisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phisActionPerformed
        this.setVisible(false);
        Purchasehis.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_phisActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.setVisible(false);
        Sales.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void shisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shisActionPerformed
        this.setVisible(false);
        Saleshis.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_shisActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);
        Stockrepo.main(new String[1]);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home1ActionPerformed
        this.setVisible(false);
        Accountsyst.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_home1ActionPerformed

    private void item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item1ActionPerformed
        this.setVisible(false);
        Addproduct.main(new String[3]);

    }//GEN-LAST:event_item1ActionPerformed

    private void customer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer2ActionPerformed
        this.setVisible(false);
        Customer.main(new String[2]);
    }//GEN-LAST:event_customer2ActionPerformed

    private void ven1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ven1ActionPerformed
        this.setVisible(false);
        Vendor.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_ven1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.setVisible(false);
        Find.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.setVisible(false);
        Purchase.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void phis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phis1ActionPerformed
        this.setVisible(false);
        Purchasehis.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_phis1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        this.setVisible(false);
        Sales.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void shis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shis1ActionPerformed
        this.setVisible(false);
        Saleshis.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_shis1ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        this.setVisible(false);
        Stockrepo.main(new String[1]);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Find().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable customer;
    private javax.swing.JMenuItem customer1;
    private javax.swing.JMenuItem customer2;
    private javax.swing.JMenuItem home;
    private javax.swing.JMenuItem home1;
    private javax.swing.JMenuItem item;
    private javax.swing.JMenuItem item1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem phis;
    private javax.swing.JMenuItem phis1;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchbar;
    private javax.swing.JMenuItem shis;
    private javax.swing.JMenuItem shis1;
    private javax.swing.JMenuItem ven;
    private javax.swing.JMenuItem ven1;
    private javax.swing.JTable vendor;
    // End of variables declaration//GEN-END:variables
}
