/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package accounting.system;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nayan
 */
public class Purchasehis extends javax.swing.JFrame {

    /** Creates new form Purchasehis */
    public Purchasehis() {
        initComponents();
        repo();
    }
    void repo()
    {
       try{
        Connection con=Connect.getconn();
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("select * from purchase order by id");
        while(rs.next())
        {
            String id=String.valueOf(rs.getInt("id"));
            String item=rs.getString("item");
            String sname=rs.getString("sname");
            String scity=rs.getString("scity");
            String qty=String.valueOf(rs.getInt("qty"));
            String pprice=String.valueOf(rs.getInt("pprice"));
            String total=String.valueOf(rs.getInt("total"));
            String pdate=rs.getString("pdate");
            String invno=String.valueOf(rs.getInt("invno"));
            String phone=rs.getString("phone");
            
            String tbData[]={id,invno,item,sname,scity,qty,pprice,total,pdate,phone};
            DefaultTableModel tb1Model=(DefaultTableModel)phis.getModel();
            tb1Model.addRow(tbData);
        }
        
                }catch(Exception tt)
                {
                    System.out.println(tt);
                }
                }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        home = new javax.swing.JMenuItem();
        item = new javax.swing.JMenuItem();
        customer = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        phis = new javax.swing.JTable();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        home2 = new javax.swing.JMenuItem();
        item2 = new javax.swing.JMenuItem();
        customer2 = new javax.swing.JMenuItem();
        ven = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        phis2 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        shis = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();

        jMenuBar1.setBackground(new java.awt.Color(102, 0, 153));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setForeground(new java.awt.Color(153, 0, 153));
        jMenuBar1.setAlignmentY(0.5F);
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu1.setText("Account Master       ");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        home.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jMenu1.add(home);

        item.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        item.setText("Item");
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActionPerformed(evt);
            }
        });
        jMenu1.add(item);

        customer.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        customer.setText("Customer");
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        jMenu1.add(customer);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Purchase          ");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuItem2.setText("Purchase Form");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sales             ");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuItem3.setText("Sales Form");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Report           ");
        jMenu5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuItem1.setText("STOCK");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuItem4.setText("Purchase");
        jMenu5.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuItem5.setText("Sales");
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Purchase History");

        phis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "INVOICE NO.", "ITEM", "VENDOR", "CITY", "QTY", "PRICE", "TOTAL", "DATE", "PHONE"
            }
        ));
        phis.setSelectionForeground(new java.awt.Color(255, 0, 51));
        jScrollPane1.setViewportView(phis);
        if (phis.getColumnModel().getColumnCount() > 0) {
            phis.getColumnModel().getColumn(3).setMinWidth(200);
            phis.getColumnModel().getColumn(3).setPreferredWidth(200);
            phis.getColumnModel().getColumn(3).setMaxWidth(200);
            phis.getColumnModel().getColumn(4).setMinWidth(170);
            phis.getColumnModel().getColumn(4).setPreferredWidth(170);
            phis.getColumnModel().getColumn(4).setMaxWidth(170);
        }

        jMenuBar3.setBackground(new java.awt.Color(102, 0, 153));
        jMenuBar3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar3.setForeground(new java.awt.Color(153, 0, 153));
        jMenuBar3.setAlignmentY(0.5F);
        jMenuBar3.setBorderPainted(false);
        jMenuBar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu9.setText("Account Master       ");
        jMenu9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        home2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        home2.setText("Home");
        home2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home2ActionPerformed(evt);
            }
        });
        jMenu9.add(home2);

        item2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        item2.setText("Item");
        item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item2ActionPerformed(evt);
            }
        });
        jMenu9.add(item2);

        customer2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        customer2.setText("Customer");
        customer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer2ActionPerformed(evt);
            }
        });
        jMenu9.add(customer2);

        ven.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ven.setText("Vendor");
        ven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venActionPerformed(evt);
            }
        });
        jMenu9.add(ven);

        jMenuBar3.add(jMenu9);

        jMenu10.setText("Purchase          ");
        jMenu10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jMenuItem10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuItem10.setText("Purchase Form");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem10);

        phis2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        phis2.setText("Purchase History");
        phis2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phis2ActionPerformed(evt);
            }
        });
        jMenu10.add(phis2);

        jMenuBar3.add(jMenu10);

        jMenu11.setText("Sales             ");
        jMenu11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jMenuItem11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuItem11.setText("Sales Form");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem11);

        shis.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        shis.setText("Sales History");
        shis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shisActionPerformed(evt);
            }
        });
        jMenu11.add(shis);

        jMenuBar3.add(jMenu11);

        jMenu12.setText("Report           ");
        jMenu12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jMenuItem12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jMenuItem12.setText("STOCK");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem12);
        jMenu12.add(jSeparator1);

        jMenuBar3.add(jMenu12);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1128, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        this.setVisible(false);
        Accountsyst.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActionPerformed
        this.setVisible(false);
        Addproduct.main(new String[3]);
    }//GEN-LAST:event_itemActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        this.setVisible(false);
        Customer.main(new String[2]);
    }//GEN-LAST:event_customerActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setVisible(false);
        Purchase.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.setVisible(false);
        Sales.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);
        Stockrepo.main(new String[1]);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void home2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home2ActionPerformed
        this.setVisible(false);
        Accountsyst.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_home2ActionPerformed

    private void item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item2ActionPerformed
        this.setVisible(false);
        Addproduct.main(new String[3]);
    }//GEN-LAST:event_item2ActionPerformed

    private void customer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer2ActionPerformed
        this.setVisible(false);
        Customer.main(new String[2]);
    }//GEN-LAST:event_customer2ActionPerformed

    private void venActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venActionPerformed
        this.setVisible(false);
        Vendor.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_venActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        this.setVisible(false);
        Purchase.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void phis2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phis2ActionPerformed
        this.setVisible(false);
        Purchasehis.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_phis2ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        this.setVisible(false);
        Sales.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void shisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shisActionPerformed
        this.setVisible(false);
        Saleshis.main(new String[2]);

        // TODO add your handling code here:
    }//GEN-LAST:event_shisActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        this.setVisible(false);
        Stockrepo.main(new String[1]);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchasehis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchasehis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchasehis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchasehis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchasehis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem customer;
    private javax.swing.JMenuItem customer2;
    private javax.swing.JMenuItem home;
    private javax.swing.JMenuItem home2;
    private javax.swing.JMenuItem item;
    private javax.swing.JMenuItem item2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable phis;
    private javax.swing.JMenuItem phis2;
    private javax.swing.JMenuItem shis;
    private javax.swing.JMenuItem ven;
    // End of variables declaration//GEN-END:variables

}
